# Generated by Django 2.1.7 on 2019-03-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cep',
            field=models.PositiveIntegerField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email_emergencia1',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email_emergencia2',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome_emergencia1',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome_emergencia2',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='numero',
            field=models.PositiveIntegerField(max_length=6, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='profissao',
            field=models.CharField(max_length=40, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.CharField(choices=[('FEM', 'Feminino'), ('MASC', 'Masculino'), ('NB', 'Não binário')], default='FEM', max_length=2, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tel_emergencia1',
            field=models.PositiveIntegerField(max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tel_emergencia2',
            field=models.PositiveIntegerField(max_length=11, verbose_name='Telefone'),
        ),
    ]
