# Generated by Django 2.1.7 on 2019-03-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190316_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='numero',
        ),
    ]
