# Generated by Django 2.1.7 on 2019-03-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_remove_cadastro_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.CharField(choices=[('FEM', 'Feminino'), ('MASC', 'Masculino'), ('NB', 'Não binário')], default='FEM', max_length=1, verbose_name='Gênero'),
        ),
    ]
