# Generated by Django 2.1.7 on 2019-03-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20190318_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
    ]
